env:
    # Cirrus Specific .Var.s (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "Build crdroid"
  timeout_in: 180m
  container:
      image: ghcr.io/catthehacker/ubuntu:act-18.04
      cpu: 8
      memory: 32G

  Sync_script:
      - apt update
      - apt install curl -y
      - curl -sL https://github.com/bread-up/my_tools-2/raw/rom/sync.sh | bash
